Codingclub2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', include('chemhunt.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chemhunt/urls.py
from django.conf.urls import url, include
from .import views


app_name = 'chemhunt'

urlpatterns = [

    url(r'^test/$', views.test, name='test'),

    url(r'^$', views.main, name='main'),

    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    url(r'^(?P<pk>[0-9]+)/answer/$', views.answer, name='answer'),

    url(r'^(?P<pk>[0-9]+)/skip/$', views.skip, name='skip'),

    url(r'^main/$', views.main, name='main'),

    url(r'^index/$', views.index, name='index'),




            ]

chemhunt/models.py
from django.db import models
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth.models import User


class Player(models.Model):
    name = models.OneToOneField(User, null=True)
    rank = models.IntegerField(blank=True, null=True)
    score = models.IntegerField(default=0)
    question_no = models.IntegerField(default=1, blank=True)
    answers_given = models.CharField(max_length=100, default="000000000000000000000000000000000000")

    def __str__(self):
        return str(self.name)


class Question(models.Model):
    question_no = models.IntegerField(blank=True, default=1)
    question = models.CharField(max_length=10000)
    solution = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.question_no)

chemhunt/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Question


class AnswerForm(forms.Form):
    answerof = forms.CharField(max_length=10000)

Codingclub2/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views import generic
from django.views.generic import View, FormView
from django.core.urlresolvers import reverse

from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import auth
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404


def main(request):
    return HttpResponseRedirect('/accounts/login')

chemhunt/views.py
from django.shortcuts import render

# Create your views here.
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views import generic
from django.views.generic import View, FormView
from django.core.urlresolvers import reverse

from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import auth
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Player, Question
from .forms import AnswerForm








def test(request):
    return render(request, 'chemhunt/test.html')


def main(request):
    user = request.user
    try:
        up = Player()
        up.name = user
        up.save()
    except:
        up = Player.objects.get(name=user)

    return HttpResponseRedirect('/accounts/profile/index')


class IndexView(generic.ListView):
    template_name = 'chemhunt/index.html'

    def get_queryset(self):
        return Question.objects.all()


class DetailView(generic.DetailView):
    model = Question
    template_name = 'chemhunt/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_pk = self.kwargs['pk']
        product = Question.objects.get(pk=product_pk)
        context.update({
            'product': product,


        })
        return context


def detail(request, pk):
    error = False
    product = Question.objects.get(pk=pk)
    user = request.user
    up = Player.objects.get(name=user)

    if up.question_no == product.question_no:
        list1 = list(up.answers_given)
        if list1[product.question_no] == '3':
            error = True

        leaderboard = Player.objects.order_by('score').reverse()
        i = 0

        for player in leaderboard:
            if up.score == player.score:
                up.rank = i + 1
                up.save()
            else:
                i += 1
        up.save()
        s = up.answers_given.count('2')
        skips = 1 - s
        return render(request, 'chemhunt/detail.html',
                      {'product': product, 'player': up, 'skips': skips,  'error': error})
    else:
        return HttpResponseRedirect('/accounts/logout/')




def index(request):
    user = request.user
    up = Player.objects.get(name=user)

    leaderboard = Player.objects.order_by('score').reverse()
    i = 0

    for player in leaderboard:
        if up.score == player.score:
            up.rank = i + 1
            up.save()
        else:
            i += 1
    up.save()
    s = up.answers_given.count('2')
    skips = 1 - s

    return render(request, 'chemhunt/index.html', {'player': up, "skips": skips, 'leaderboard': leaderboard})






def answer(request, pk):
    question = Question.objects.get(pk=pk)
    answerof = request.POST['answerof']

    user = request.user
    up = Player.objects.get(name=user)

    leaderboard = Player.objects.order_by('score').reverse()
    i = 0

    for player in leaderboard:
        if up.score == player.score:
            up.rank = i + 1
            up.save()
        else:
            i += 1
    up.save()

    if answerof == question.solution:
        list1 = list(up.answers_given)
        list1[question.question_no] = '1'
        up.answers_given = ''.join(list1)
        up.question_no += 1
        up.save()
        error = False
    else:
        list1 = list(up.answers_given)
        list1[question.question_no] = '3'
        up.answers_given = ''.join(list1)
        up.save()
        return HttpResponseRedirect('/accounts/profile/%s/' % pk)

    c = up.answers_given.count('1')
    s = up.answers_given.count('2')
    up.score = (c * 100) - (s * 25)
    up.save()
    return HttpResponseRedirect('/accounts/profile/%s/' % up.question_no, {'error': error})


def skip(request, pk):
    question = Question.objects.get(pk=pk)
    user = request.user
    up = Player.objects.get(name=user)
    s = up.answers_given.count('2')

    if s < 1:
        list1 = list(up.answers_given)
        list1[question.question_no] = '2'
        up.answers_given = ''.join(list1)
        up.question_no += 1
        up.save()
        c = up.answers_given.count('1')
        s = up.answers_given.count('2')
        up.score = (c * 100) - (s * 25)
        up.save()
        return HttpResponseRedirect('/accounts/profile/%s/' % up.question_no)

    else:
        return HttpResponseRedirect('/accounts/profile/%s/' % pk)

templates/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% load staticfiles %}
    <title>ChemHunt| Login</title>

    <link rel="stylesheet" href="{% static 'chemhunt/css/bootstrap.min.css' %}">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="{% static 'chemhunt/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'chemhunt/css/style.css' %}" rel="stylesheet">
    <script type='text/javascript' src="{% static 'chemhunt/js/jquery-2.1.1.js' %}"></script>
    <script type='text/javascript' src="{% static 'chemhunt/js/bootstrap.min.js' %}"></script>

</head>
  <body class="gray-bg">

    {% block body %}


    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

templates/chemhunt/answer.html
{%  extends 'chemhunt/base.html' %}

{% block body %}

<h3>Do you really want to sign for {{ product.name }} ?</h3>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {%  csrf_token %}
        <input type="hidden" name="name" value="{{ product.question }}">
        <input type="hidden" name="date" value="">

{{ context.question }}
{{ item.question }}
        <input type="hidden" name="accepted" value="Yes">

       <button type="submit" class="btn btn-success"> Allow</button>



    </form>





{% endblock %}

templates/chemhunt/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <title>ChemHunt</title>
      <meta charset="utf-8">
      <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <style>
      .blue{background-color:#2196F3 !important}
      .circle{border-radius:50%}
      .btn-primary.btn-outline {
  color: #2f4050;
}
.btn-primary {
	margin-top: 30px;
	width: 15%;
	padding: 1%;
	font-size: 18px;
  background-color: #0d47a1;
  border-color: #0d47a1;
  color: #fff;
  border-radius: 0;
}
.btn-primary:hover {
  background-color: #092b61;
}
.btn-primary:focus,
.btn-primary:active,
.btn-primary.active,
.open .dropdown-toggle.btn-primary {
 background-color: #092b61;
  border-color: #092b61;
  color: #fff;
}
      body{
      	font-family:'Roboto', sans-serif;
      }
       #ele1{
         color: #bdbdbd;
         font-size: 15px;
      }
      #ele{
         color: #bdbdbd;
      }
      #ele:hover{
         color: #0d47a1;

      }

      </style>
   </head>

<body>

{%  block body %}
{% endblock %}



</body>
</html>

templates/chemhunt/detail.html
{% extends 'chemhunt/base.html' %}

<title>{%  block title %}{% endblock %}</title>

{%  block body %}



<div class="col-xs-9" style="background-color: #fafafa; height: 100vh; ">
<p style="font-size:60px;margin-top:4px;padding:20px; color: #bdbdbd;">ChemHunt</p>

<div class="col-xs-12" style="background-color:transparent; border-bottom:#e7e7e7 solid 0.5px; padding: 0px; margin:0px; margin-top: 10px;">
   <div class="col-xs-3" style="margin: 0px; margin-left:12.5%;" align="center">
   <p  data-toggle="modal" data-target="#instruction" id="ele">Instruction</p>
   </div>
   <div class="col-xs-3" align="center">
   <p data-toggle="modal" data-target="#leaderboard" id="ele">Leaderboard</p>
   </div>
   <div class="col-xs-3" align="center">
       <a href="/accounts/logout/"><p id="ele">Logout</p></a>
   </div>


</div>
<div class="row">
<div class="col-xs-12" style="margin-left: 25%; margin-top: 10%;">
	<div class="col-xs-6">
    <p id="ele1">Question <span id="question_number">{{ product.id}}</span></p>
	<p style="color: #848484;"> {{ product.question }} </p>
	</div><br><br>
	<hr style="color: #e2e2e2; width: 45%; margin-left: -2.5%;">
	<p id="ele1">Question <span id="question_number">{{ product.id}}</span></p>


    {% if error %}
       Wrong answer Pls try again
    {% endif %}

	<form action="{% url 'chemhunt:answer' product.id  %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
        <div class="form-group">

              <input type="text" class="form-control" name="answerof" id="answerof" style="width: 40%;" required="required">
              <button class="btn btn-primary"
                                        type="submit">Submit </button>

            <a href="{% url 'chemhunt:skip' product.id  %}"><button class="btn btn-primary" type="button" style="margin-left: 10%; background-color: #eaeaea; color: #000; border: none;">Skip </button></a>
                                        </div>
                                        </form>


</div>
</div>
  </div>
<div class="col-xs-3" style="height:100vh;background:#0d47a1; padding: 50px;">
   <h2 style="font-family: 'Roboto', sans-serif; color:#fafafa; margin-top: 8vh; letter-spacing: 1px;">Chem Hunt</h2>
    <br><br>
    <div class="col-xs-2" style="padding:0px;margin:0px;">
    <i class="medium material-icons" style="margin-top:0px; color: #fff;">assignment_ind</i>
    </div>
    <div class="col-xs-10" style="padding:0px;margin:0px;">
    <p style="font-size:16px;font-family:'Roboto', sans-serif;color:#fafafa;font-weight:lighter;margin-top:3px;">
    <span id="user.username">{% if request.user.is_authenticated  %}
    {{ user.socialaccount_set.all.0.extra_data.name }}
    {% endif %}</span></p>
    </div>
    <br>
    <div class="col-xs-2" style="padding:0px;margin:0px;">
    <i class="medium material-icons" style="margin-top:0px; color: #fff;">stars</i>
    </div>
    <div class="col-xs-10" style="padding:0px;margin:0px;">
    <p style="font-size:16px;font-family:'Roboto', sans-serif;color:#fafafa;font-weight:lighter;margin-top:3px;">
    <span id="user.points">{{ player.score }}</span></p>
    </div>
    <br>
    <div class="col-xs-2" style="padding:0px;margin:0px;">
    <i class="medium material-icons" style=" color: #fff;">perm_identity</i>
    </div>
    <div class="col-xs-10" style="padding:0px;margin:0px;">
    <p style="font-size:16px;font-family:'Roboto', sans-serif;color:#fafafa;font-weight:lighter; margin-top: 3px;">
    <span id="user.rank">{{ player.rank }}</span></p>
     <p style="font-family:'Roboto', sans-serif;font-size:18px; color:#fafafa; font-weight:lighter; margin-top:40vh; margin-left: -45px;">You have <span style="font-weight: bold;"> 1 </span> Skips left</p>

    </div>
   <footer>
   <p style="font-family:'Roboto', sans-serif;font-size:12px;color:#fafafa;font-weight:lighter;margin-top:61vh;">An event by Coding Club and Chemical Engineering Association</p>
   </footer>

   </div>

   <div class="modal fade" tabindex="-1" role="dialog" id="instruction">
  <div class="modal-dialog" role="document" >
    <div class="modal-content" style="border-radius: 0;">
      <div class="modal-header" style="background-color: #0d47a1;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" align="center" style="padding: 20px; color: #fff;"> Instructions</h3>
      </div>
      <div class="modal-body">
        <p style="color:#000000;"> Welcome to the game. In this section here are some of the points to be kept in mind while playing the game<br><br>

	  <b>You will have 1 skip which you will get when you click the skip button in the game. But remember that skip will cause you a loss of 25 points.</b><br>      Type your answer in the area provided below the question and then click on submit button in order to check if you are correct or not.<br><br>
	  Each correct answer will fetch you 100 points!!!. <br><br>
	  <b> Enter the answers with first letter capital and with spaces in between two words. </b>
	  <br><br><br>

	  After reading the manual, prepare your mind for some exciting and head notching questions.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




  <div class="modal fade" tabindex="-1" role="dialog" id="leaderboard">
  <div class="modal-dialog" role="document" >
    <div class="modal-content" style="border-radius: 0; background-color: #fafafa">
      <div class="modal-header" style="background-color: #0d47a1;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" align="center" style="padding: 20px; color: #fff;">Leaderboard </h3>
      </div>
      <div class="modal-body" style="background-color: #fafafa; height: 100vh;">
       <div class="col-xs-12" style="border: 1px solid #bdbdbd; background-color: #fff ">
       	{% for player in leaderboard %}
           <div class="col-xs-2">
 <i class="material-icons circle blue" style="color: #fff; padding: 10px; margin-top: 10px; margin-bottom: 10px;">perm_identity</i>
       	</div>
       	<div class="col-xs-9" align="left" style="margin-bottom: 10px;">
       	  <p style="font-size:20px; padding-top: 10px;" >Name: {{ player.name }} </p>
      <span style="padding-top:1vh;">Points: {{ player.score }}  <br>


      </span>
       	</div>
           {% endfor %}
<br>
       </div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




<script type="text/javascript">
    $(window).load(function(){
        $('#welcoe').modal('show');
    });
</script>
</body>
</html>


{% endblock %}

templates/chemhunt/index.html
{% extends 'chemhunt/base.html' %}

<title>{%  block title %}{% endblock %}</title>

{%  block body %}



<div class="col-xs-9" style="background-color: #fafafa; height: 100vh; ">
<p style="font-size:60px;margin-top:4px;padding:20px; color: #bdbdbd;">ChemHunt</p>

<div class="col-xs-12" style="background-color:transparent; border-bottom:#e7e7e7 solid 0.5px; padding: 0px; margin:0px; margin-top: 10px;">
   <div class="col-xs-3" style="margin: 0px; margin-left:12.5%;" align="center">
   <p  data-toggle="modal" data-target="#instruction" id="ele">Instruction</p>
   </div>
   <div class="col-xs-3" align="center">
   <p data-toggle="modal" data-target="#leaderboard" id="ele">Leaderboard</p>
   </div>
   <div class="col-xs-3" align="center">
       <a href="/accounts/logout/"><p id="ele">Logout</p></a>
   </div>


</div>
<div class="row">
<div class="col-xs-12" style="margin-left: 25%; margin-top: 10%;">

 <div class="middle-box text-center logincreen animated fadeInDown">
        <div>

            <br>
            <p style="font-size: 16px; line-height: 30px;">Assume that BITS runs on bio gas electricity and due to an

accident, the bio gas resources have abruptly been depleted

and the campus runs out of power. And since the campus is

full of energy and is loaded with a technological extravaganza

that is Apogee, you need power and you have run out of

resources. The fest begins in half an hour. Now, you need

appropriate reactants and reagents to produce biogas but

you are not sure where to find them on campus. Luckily, your

chemistry professor has left you a huge mind blowing clue

base to find these chemicals and their locations. Now, using

your knowledge of basic chemistry and even more

importantly, your knowledge of BITS as your campus try to

figure out where and what these chemicals are in your

campus and find out how you will produce this biogas and

supply it to your power plant at BITS.

These are what are left in the clue base given by your

professor: <br> <br>
<a href="{% url 'chemhunt:detail' player.question_no  %}">
  <button class="btn btn-primary" type="submit" style="width: 200px;"> Continue </button></a>
</p>


        </div>
    </div>

</div>
</div>
  </div>
<div class="col-xs-3" style="height:100vh;background:#0d47a1; padding: 50px;">
   <h2 style="font-family: 'Roboto', sans-serif; color:#fafafa; margin-top: 8vh; letter-spacing: 1px;">Chem Hunt</h2>
    <br><br>
    <div class="col-xs-2" style="padding:0px;margin:0px;">
    <i class="medium material-icons" style="margin-top:0px; color: #fff;">assignment_ind</i>
    </div>
    <div class="col-xs-10" style="padding:0px;margin:0px;">
    <p style="font-size:16px;font-family:'Roboto', sans-serif;color:#fafafa;font-weight:lighter;margin-top:3px;">
    <span id="user.username">{% if request.user.is_authenticated  %}
    {{ user.socialaccount_set.all.0.extra_data.name }}
    {% endif %}</span></p>
    </div>
    <br>
    <div class="col-xs-2" style="padding:0px;margin:0px;">
    <i class="medium material-icons" style="margin-top:0px; color: #fff;">stars</i>
    </div>
    <div class="col-xs-10" style="padding:0px;margin:0px;">
    <p style="font-size:16px;font-family:'Roboto', sans-serif;color:#fafafa;font-weight:lighter;margin-top:3px;">
    <span id="user.points">{{ player.score }}</span></p>
    </div>
    <br>
    <div class="col-xs-2" style="padding:0px;margin:0px;">
    <i class="medium material-icons" style=" color: #fff;">perm_identity</i>
    </div>
    <div class="col-xs-10" style="padding:0px;margin:0px;">
    <p style="font-size:16px;font-family:'Roboto', sans-serif;color:#fafafa;font-weight:lighter; margin-top: 3px;">
    <span id="user.rank">{{ player.rank }}</span></p>
     <p style="font-family:'Roboto', sans-serif;font-size:18px; color:#fafafa; font-weight:lighter; margin-top:40vh; margin-left: -45px;">You have <span style="font-weight: bold;"> 1 </span> Skips left</p>

    </div>
   <footer>
   <p style="font-family:'Roboto', sans-serif;font-size:12px;color:#fafafa;font-weight:lighter;margin-top:61vh;">An event by Coding Club and Chemical Engineering Association</p>
   </footer>

   </div>

   <div class="modal fade" tabindex="-1" role="dialog" id="instruction">
  <div class="modal-dialog" role="document" >
    <div class="modal-content" style="border-radius: 0;">
      <div class="modal-header" style="background-color: #0d47a1;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" align="center" style="padding: 20px; color: #fff;"> Instructions</h3>
      </div>
      <div class="modal-body">
        <p style="color:#000000;"> Welcome to the game. In this section here are some of the points to be kept in mind while playing the game<br><br>

	  <b>You will have 1 skip which you will get when you click the skip button in the game. But remember that skip will cause you a loss of 25 points.</b><br>      Type your answer in the area provided below the question and then click on submit button in order to check if you are correct or not.<br><br>
	  Each correct answer will fetch you 100 points!!!. <br><br>
	  <b> Enter the answers with first letter capital and with spaces in between two words. </b>
	  <br><br><br>

	  After reading the manual, prepare your mind for some exciting and head notching questions.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




  <div class="modal fade" tabindex="-1" role="dialog" id="leaderboard">
  <div class="modal-dialog" role="document" >
    <div class="modal-content" style="border-radius: 0; background-color: #fafafa">
      <div class="modal-header" style="background-color: #0d47a1;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" align="center" style="padding: 20px; color: #fff;">Leaderboard </h3>
      </div>
      <div class="modal-body" style="background-color: #fafafa; height: 100vh;">
       <div class="col-xs-12" style="border: 1px solid #bdbdbd; background-color: #fff ">
       	{% for player in leaderboard %}
           <div class="col-xs-2">
 <i class="material-icons circle blue" style="color: #fff; padding: 10px; margin-top: 10px; margin-bottom: 10px;">perm_identity</i>
       	</div>
       	<div class="col-xs-9" align="left" style="margin-bottom: 10px;">
       	  <p style="font-size:20px; padding-top: 10px;" >Name: {{ player.name }} </p>
      <span style="padding-top:1vh;">Points: {{ player.score }}  <br>


      </span>
       	</div>
           {% endfor %}
<br>
       </div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




<script type="text/javascript">
    $(window).load(function(){
        $('#welcoe').modal('show');
    });
</script>
</body>
</html>


{% endblock %}

templates/chemhunt/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Welcome
<p> {% if request.user.is_authenticated  %}


        {{ user.socialaccount_set.all.0.extra_data.name }}


    {% endif %}</p>


<a href="{% url 'chemhunt:detail' player.question_no %}">Lets Go</a>
</body>
</html>